packages:
  - packages/*
  - ohos-typescript
catalogs:
  build:
    tsdown: 0.16.4
  dev:
    fast-glob: ^3.3.3
    reactive-vscode: ^0.3.2
    rimraf: ^6.0.1
    ts-macro: ^0.3.6
    type-fest: ^4.41.0
    vscode-ext-gen: ^1.1.0
  frontend:
    '@iconify-json/ph': ^1.2.2
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    '@vueuse/core': 13.9.0
    markdown-it: ^14.1.0
    naive-ui: ^2.43.1
    nprogress: ^0.2.0
    pinia: ^3.0.3
    unocss: ^66.5.1
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.16.1
    vite: npm:rolldown-vite@latest
    vite-plugin-vue-layouts: ^0.11.0
    vue: ^3.5.21
    vue-i18n: ^11.1.12
    vue-router: ^4.6.3
  lint:
    '@antfu/eslint-config': latest
    eslint: latest
    oxlint: ^1.16.0
  polyfill:
    path-browserify: ^1.0.1
    reflect-metadata: ^0.2.2
  prod:
    '@arkts/project-detector': ^1.1.3-alpha.29
    '@arkts/project-detector-android-arm-eabi': ^1.1.3-alpha.29
    '@arkts/project-detector-android-arm64': ^1.1.3-alpha.29
    '@arkts/project-detector-darwin-arm64': ^1.1.3-alpha.29
    '@arkts/project-detector-darwin-x64': ^1.1.3-alpha.29
    '@arkts/project-detector-freebsd-x64': ^1.1.3-alpha.29
    '@arkts/project-detector-linux-arm-gnueabihf': ^1.1.3-alpha.29
    '@arkts/project-detector-linux-arm64-gnu': ^1.1.3-alpha.29
    '@arkts/project-detector-linux-arm64-musl': ^1.1.3-alpha.29
    '@arkts/project-detector-linux-x64-gnu': ^1.1.3-alpha.29
    '@arkts/project-detector-linux-x64-musl': ^1.1.3-alpha.29
    '@arkts/project-detector-openharmony-arm64': ^1.1.3-alpha.29
    '@arkts/project-detector-openharmony-x64': ^1.1.3-alpha.29
    '@arkts/project-detector-wasm32-wasi': ^1.1.3-alpha.29
    '@arkts/project-detector-win32-arm64-msvc': ^1.1.3-alpha.29
    '@arkts/project-detector-win32-ia32-msvc': ^1.1.3-alpha.29
    '@arkts/project-detector-win32-x64-msvc': ^1.1.3-alpha.29
    '@arkts/sdk-downloader': ^0.1.30
    '@types/lodash': ^4.17.20
    '@types/unzipper': ^0.10.11
    '@volar/language-core': ~2.4.23
    '@volar/language-server': ~2.4.23
    '@volar/typescript': ~2.4.23
    '@volar/vscode': ~2.4.23
    '@vscode/l10n': ^0.0.18
    alien-signals: ^3.0.3
    axios: ^1.12.2
    birpc: ^2.6.1
    chokidar: ^4.0.3
    consola: ^3.4.2
    defu: ^6.1.4
    extract-zip: ^2.0.1
    fflate: ^0.8.2
    handlebars: ^4.7.8
    json5: ^2.2.3
    kleur: ^4.1.5
    lodash: ^4.17.21
    mitt: ^3.0.1
    nanoid: ^5.1.6
    readdirp: ^4.1.2
    tar: ^7.4.3
    typescript: latest
    unioc: ^0.0.21
    unzipper: ^0.12.3
    volar-service-css: volar-2.4
    volar-service-emmet: volar-2.4
    volar-service-html: volar-2.4
    volar-service-typescript: volar-2.4
    vscode-html-languageservice: ^5.5.1
    vscode-languageserver-protocol: ^3.17.5
    vscode-languageserver-textdocument: ^1.0.12
    vscode-languageserver-types: ^3.17.5
    vscode-nls: ^5.2.0
    vscode-uri: ^3.1.0
  scripts:
    '@antfu/nip': ^0.1.0
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.29.7
    '@vscode/vsce': latest
    cross-env: ^10.0.0
    html5parser: ^2.0.2
    magic-string: ^0.30.19
    ovsx: ^0.10.5
    oxc-parser: ^0.90.0
    oxc-walker: ^0.5.2
    pnpm: ^10.17.0
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.5
  test:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    vitest: ^3.2.4
  types:
    '@types/markdown-it': ^14.1.2
    '@types/node': latest
    '@types/nprogress': ^0.2.3
    '@types/progress-stream': ^2.0.5
    '@types/vscode': ^1.104.0
dedupeInjectedDeps: false
linkWorkspacePackages: true
lockfile: true
nodeLinker: isolated
recursiveInstall: true
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - simple-git-hooks
  - unrs-resolver
publicHoistPattern:
  - '@arkts/project-detector'
  - '@arkts/project-detector-*'
  - mitt
  - alien-signals
  - chokidar
  - '@napi-rs/wasm-runtime'
